services:
  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: ${POSTGRES_DB}
      POSTGRES_DB: hackatum-22
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    container_name: api
    build:
      context: ./api 
    ports:
      - '8000:8000'
    restart: on-failure 

